### ISSUE TITLE
Request for new function to get all holidays by state and year 

### ISSUE THREAD

**Issue by smika01** [creios/angular-german-holidays#1]
Hello,
I like your library and use this in one of my projects. But I need a function to get all holidays by year and state in an array with date of holiday and description of holiday.

I did create this for my project in a fork. What are your contribution guidelines to take this as a PR in your library?
Thanks for your support!
Regards
Sebastian

**Comment by timtegeler** [comment]
Hi,
thank you for message. 

Your new function sounds interesting. On friday i meet up with @MazeChaZer and we are going to discuss it.

At the moment we don't have a guideline for PRs. But generally PRs are welcome. :)

**Comment by smika01** [comment]
Ok, I will send my PR asap. 
Regards
Sebastian
